name: PR

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/build-container

on: [pull_request]

jobs:

  test-docker:
    name: Docker Build
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    steps:
      - uses: actions/checkout@v3
      - run: docker pull $IMAGE_NAME:latest || true
      - run: docker build --cache-from $IMAGE_NAME:latest .
